/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.Color;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author thamashikumarasinghe
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
        initComponents();
        this.getContentPane().setBackground(Color.PINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headingLabel = new javax.swing.JLabel();
        firstnameLabel = new javax.swing.JLabel();
        firstnameTxtField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        lastnameTxtField = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        messageLabel = new javax.swing.JLabel();
        messageTxtField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        uploadImgBtn = new javax.swing.JButton();
        firstnameValidation = new javax.swing.JLabel();
        lastnameValidation = new javax.swing.JLabel();
        ageValidation = new javax.swing.JLabel();
        emailValidation = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 255, 255));

        headingLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        headingLabel.setText("Registration Form");

        firstnameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        firstnameLabel.setText("First name");

        firstnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                firstnameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                firstnameTxtFieldFocusLost(evt);
            }
        });
        firstnameTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstnameTxtFieldMouseExited(evt);
            }
        });

        lastnameLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lastnameLabel.setText("Last name");

        lastnameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lastnameTxtFieldFocusLost(evt);
            }
        });

        ageLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        ageLabel.setText("Age");

        ageTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageTxtFieldFocusLost(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        emailTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailTxtFieldFocusLost(evt);
            }
        });

        messageLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        messageLabel.setText("Message");

        submitBtn.setBackground(new java.awt.Color(51, 153, 255));
        submitBtn.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("SUBMIT");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        uploadImgBtn.setBackground(new java.awt.Color(204, 204, 204));
        uploadImgBtn.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        uploadImgBtn.setText("Upload Image");
        uploadImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadImgBtnActionPerformed(evt);
            }
        });

        firstnameValidation.setForeground(new java.awt.Color(255, 0, 0));

        lastnameValidation.setForeground(new java.awt.Color(255, 0, 0));

        ageValidation.setForeground(new java.awt.Color(255, 0, 51));

        emailValidation.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ageValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(headingLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(submitBtn)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uploadImgBtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lastnameLabel)
                                                .addComponent(firstnameLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lastnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(firstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ageLabel)
                                                .addComponent(emailLabel))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(messageLabel)
                                            .addGap(99, 99, 99)
                                            .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(emailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lastnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(firstnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(headingLabel)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameLabel)
                    .addComponent(firstnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameLabel)
                    .addComponent(lastnameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageLabel)
                    .addComponent(ageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ageValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailValidation, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageLabel)
                    .addComponent(messageTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(uploadImgBtn)
                .addGap(14, 14, 14)
                .addComponent(submitBtn)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        String firstname, lastname, age, email;
        try {
            firstname = firstnameTxtField.getText();
            lastname = lastnameTxtField.getText();
            age = ageTxtField.getText();
            email = emailTxtField.getText();
            // validation for submit button
            if (firstname == null || firstname.isEmpty()) {
                firstnameValidation.setText("First name is empty");
            }
            if (lastname == null || lastname.isEmpty()) {
                lastnameValidation.setText("Last name is empty");
            }
            if (age == null || age.isEmpty()) {
                ageValidation.setText("Age is empty");
            }
            if (email == null || email.isEmpty()) {
                emailValidation.setText("Email is empty");
            } else {
                JOptionPane.showMessageDialog(this, "User Successfully Registered!");
            }
        } catch (Exception e) {
            System.out.println("Error" + e);
//            JOptionPane.showMessageDialog(this, "Error while Registering!" + e);

        }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void uploadImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadImgBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uploadImgBtnActionPerformed

    private void firstnameTxtFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameTxtFieldMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameTxtFieldMouseExited

    private void firstnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTxtFieldFocusLost
        // TODO add your handling code here:
        if (firstnameTxtField.getText() == null || firstnameTxtField.getText().isEmpty()) {
            firstnameValidation.setText("First name is empty");
        }
    }//GEN-LAST:event_firstnameTxtFieldFocusLost

    private void firstnameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_firstnameTxtFieldFocusGained
        // TODO add your handling code here:
        firstnameValidation.setText("");
    }//GEN-LAST:event_firstnameTxtFieldFocusGained

    private void lastnameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTxtFieldFocusLost
        // TODO add your handling code here:
        if (lastnameTxtField.getText() == null || lastnameTxtField.getText().isEmpty()) {
            lastnameValidation.setText("Last name is empty");
        }
    }//GEN-LAST:event_lastnameTxtFieldFocusLost

    private void lastnameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameTxtFieldFocusGained
        // TODO add your handling code here:
        lastnameValidation.setText("");
    }//GEN-LAST:event_lastnameTxtFieldFocusGained

    private void ageTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTxtFieldFocusLost
        // TODO add your handling code here:
        try {
            if (ageTxtField.getText() == null || ageTxtField.getText().isEmpty()) {
                ageValidation.setText("Age is empty");
            } else if (ageTxtField.getText().length() > 3) {
                ageValidation.setText("Age is invalid. Please enter a valid age!");
            } else {
                for (int i = 0; i < ageTxtField.getText().length(); i++) {
                    if (Character.isDigit(ageTxtField.getText().charAt(i)) == false) {
                        ageValidation.setText("Age contains invalid characters. Please enter a valid age!");
                    }
                }

            }

        } catch (NumberFormatException e) {

        }

    }//GEN-LAST:event_ageTxtFieldFocusLost

    private void ageTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTxtFieldFocusGained
        // TODO add your handling code here:
        ageValidation.setText("");
    }//GEN-LAST:event_ageTxtFieldFocusGained

    private void emailTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFieldFocusLost
        // TODO add your handling code here:
        Pattern pattern = Pattern.compile("^(.+)@(.+)$");
        if (emailTxtField.getText() == null || emailTxtField.getText().isEmpty()) {
            emailValidation.setText("Email is empty");
        } else if (!pattern.matcher(emailTxtField.getText()).matches()) {
            emailValidation.setText("Email is Invalid. Enter a valid email");

        }
    }//GEN-LAST:event_emailTxtFieldFocusLost

    private void emailTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailTxtFieldFocusGained
        // TODO add your handling code here:
        emailValidation.setText("");
    }//GEN-LAST:event_emailTxtFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JLabel ageValidation;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JLabel emailValidation;
    private javax.swing.JLabel firstnameLabel;
    private javax.swing.JTextField firstnameTxtField;
    private javax.swing.JLabel firstnameValidation;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField lastnameTxtField;
    private javax.swing.JLabel lastnameValidation;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JTextField messageTxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton uploadImgBtn;
    // End of variables declaration//GEN-END:variables
}
